GET http://localhost:5157/feedback

###
GET http://localhost:5157/feedback/1


###
POST http://localhost:5157/feedback
Content-Type: application/json

{
	"SubID": 1, 
	"LectID": 1,
	"Comment": "No authorization exist", 
	"MarkAchieved": 40
}

###
PUT http://localhost:5157/feedback/1
Content-Type: application/json

{
	"SubID": 1, 
	"LectID": 1,
	"Comment": "No authorization exist", 
	"MarkAchieved": 50, 
	"Deleted": false
}

###
DELETE http://localhost:5157/feedback/1